# Generated by Django 3.1.1 on 2021-07-19 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_carousel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='Image',
            field=models.ImageField(upload_to='photos/'),
        ),
    ]
